import assert from "node:assert/strict";
import test from "node:test";
import mongoose from "mongoose";
import BillOfMaterials from "../src/server/models/BillOfMaterials.js";
import Product from "../src/server/models/Product.js";
import StockItem from "../src/server/models/StockItem.js";
import User from "../src/server/models/User.js";
import Warehouse from "../src/server/models/Warehouse.js";
import { checkMaterialAvailability, createBom, deleteBom, getBoms, updateBom } from "../src/server/services/bomApiService.js";
const uri = "mongodb://127.0.0.1:27018/?replicaSet=stockTestRs"; const dbName = "warehouse_system_bom_test"; const res = () => ({ statusCode: 200, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; } });
test("BOM preserves source enrichment, costs, filters, availability, update, and archive", { timeout: 120000 }, async (t) => {
  assert.equal(process.env.MONGODB_URI, uri); assert.equal(process.env.MONGODB_DB_NAME, dbName); await mongoose.connect(uri, { dbName });
  const ids = { products: [], users: [], warehouses: [], boms: [] }; const add = (group, doc) => (ids[group].push(doc._id), doc); const suffix = new mongoose.Types.ObjectId().toString().slice(-7);
  t.after(async () => { try { await Promise.all([BillOfMaterials.collection.deleteMany({ _id: { $in: ids.boms } }), StockItem.collection.deleteMany({ productId: { $in: ids.products } }), Product.collection.deleteMany({ _id: { $in: ids.products } }), Warehouse.collection.deleteMany({ _id: { $in: ids.warehouses } }), User.collection.deleteMany({ _id: { $in: ids.users } })]); } finally { await mongoose.disconnect(); } });
  const user = add("users", await User.create({ firstName: "Bom", lastName: "Test", email: `bom-${suffix}@example.test`, password: "Password9!", role: "admin" })); const finished = add("products", await Product.create({ name: `Finished ${suffix}`, categoryId: new mongoose.Types.ObjectId(), unitOfMeasure: "pcs", basePrice: 10 })); const component = add("products", await Product.create({ name: `Material ${suffix}`, productType: "raw_material", categoryId: new mongoose.Types.ObjectId(), unitOfMeasure: "kg", basePrice: 2, costs: { averageCost: 3 } })); const warehouse = add("warehouses", await Warehouse.create({ name: `BOM WH ${suffix}`, warehouseCode: `BM${suffix}`.toUpperCase() })); await StockItem.create({ productId: component._id, productCode: component.productCode, productName: component.name, warehouseId: warehouse._id, unitOfMeasure: "kg", costPerUnit: 3, quantities: { onHand: 10, reserved: 2, available: 8 } });
  const created = res(); await createBom({ user, body: { name: "Recipe", finishedProductId: String(finished._id), outputQuantity: 2, components: [{ productId: String(component._id), quantity: 4, wastagePercent: 25 }], labor: [{ hours: 2, hourlyRate: 5 }], overheadPercent: 10 } }, created); const bom = created.body.data; ids.boms.push(bom._id); assert.equal(created.statusCode, 201); assert.equal(bom.totalMaterialCost, 15); assert.equal(bom.totalLaborCost, 10); assert.equal(bom.totalCost, 27.5); assert.equal(bom.costPerUnit, 13.75); assert.equal((await Product.findById(finished._id)).canBeManufactured, true);
  const list = res(); await getBoms({ query: { search: "Recipe", status: "active", isDefault: "true", page: "1", limit: "1" } }, list); assert.equal(list.body.total, 1); const availability = res(); await checkMaterialAvailability({ params: { id: String(bom._id) }, query: { quantity: "4" } }, availability); assert.deepEqual(availability.body.data.components[0].required, 10); assert.equal(availability.body.data.components[0].available, 8); assert.equal(availability.body.data.canProduce, false);
  await updateBom({ params: { id: String(bom._id) }, user, body: { name: "Updated", components: [{ productId: String(component._id), quantity: 1, standardCost: 4 }] } }, res()); assert.equal((await BillOfMaterials.findById(bom._id)).name, "Updated"); const archived = res(); await deleteBom({ params: { id: String(bom._id) } }, archived); assert.equal(archived.body.message, "BOM archived"); assert.equal(await BillOfMaterials.findById(bom._id), null);
});
