import "server-only";
import mongoose from "mongoose";
import { getNextSequence } from "./Counter.js";
const item = new mongoose.Schema({ lineNumber: Number, productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true }, productCode: String, productName: String, salesOrderId: { type: mongoose.Schema.Types.ObjectId, ref: "SalesOrder" }, salesOrderLineId: mongoose.Schema.Types.ObjectId, invoiceId: { type: mongoose.Schema.Types.ObjectId, ref: "Invoice" }, quantityReturned: { type: Number, required: true, min: 0.01 }, unitOfMeasure: String, unitPrice: { type: Number, required: true }, reason: { type: String, enum: ["damaged_on_arrival", "defective", "wrong_item", "not_as_described", "expired", "overshipped", "customer_changed_mind", "late_delivery", "other"], required: true }, reasonDescription: String, condition: { type: String, enum: ["pending_inspection", "resellable", "repairable", "damaged", "expired", "missing"], default: "pending_inspection" }, disposition: { type: String, enum: ["pending", "restock", "repair", "scrap", "return_to_supplier", "refund_only_no_return"], default: "pending" }, refundable: { type: Boolean, default: true }, refundAmount: { type: Number, default: 0 }, restockingFeePercent: { type: Number, default: 0 }, restockingFee: { type: Number, default: 0 }, stockMovementId: { type: mongoose.Schema.Types.ObjectId, ref: "StockMovement" }, restockedAt: Date, restockedToWarehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse" }, repairOrderId: { type: mongoose.Schema.Types.ObjectId, ref: "RepairOrder" }, damageRecordId: { type: mongoose.Schema.Types.ObjectId, ref: "DamageRecord" }, photos: [String], inspectionNotes: String }, { _id: true });
const schema = new mongoose.Schema({ rmaNumber: { type: String, unique: true, trim: true, uppercase: true }, customerId: { type: mongoose.Schema.Types.ObjectId, ref: "Customer", required: true }, customerSnapshot: { name: String, code: String, phone: String }, salesOrderIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "SalesOrder" }], invoiceIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "Invoice" }], requestDate: { type: Date, default: Date.now }, receivedDate: Date, completedDate: Date, items: [item], totalReturnValue: { type: Number, default: 0 }, totalRefundAmount: { type: Number, default: 0 }, totalRestockingFees: { type: Number, default: 0 }, netRefundAmount: { type: Number, default: 0 }, status: { type: String, enum: ["draft", "approved", "awaiting_return", "received", "inspecting", "processed", "completed", "rejected", "cancelled"], default: "draft" }, returnToWarehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse" }, receivedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, inspectedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, refundMethod: { type: String, enum: ["pending", "cash_refund", "bank_refund", "credit_note", "invoice_adjustment", "none"], default: "pending" }, creditNoteId: { type: mongoose.Schema.Types.ObjectId, ref: "CreditNote" }, refundPaymentId: { type: mongoose.Schema.Types.ObjectId, ref: "Payment" }, approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, approvedAt: Date, rejectionReason: String, rejectedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, rejectedAt: Date, customerNotes: String, internalNotes: String, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, deletedAt: { type: Date, default: null } }, { timestamps: true });
schema.index({ customerId: 1, requestDate: -1 }); schema.index({ status: 1 });
schema.pre("save", async function () { if (this.isNew && !this.rmaNumber) this.rmaNumber = `RMA-${await getNextSequence("rma")}`; this.items.forEach((line, index) => { line.lineNumber = index + 1; const value = line.quantityReturned * line.unitPrice; line.restockingFee = +(value * (line.restockingFeePercent || 0) / 100).toFixed(2); if (!line.refundAmount || line.refundAmount === 0) line.refundAmount = line.refundable ? +(value - line.restockingFee).toFixed(2) : 0; }); this.totalReturnValue = +this.items.reduce((sum, line) => sum + line.quantityReturned * line.unitPrice, 0).toFixed(2); this.totalRefundAmount = +this.items.reduce((sum, line) => sum + (line.refundAmount || 0), 0).toFixed(2); this.totalRestockingFees = +this.items.reduce((sum, line) => sum + (line.restockingFee || 0), 0).toFixed(2); this.netRefundAmount = this.totalRefundAmount; });
schema.pre(/^find/, function (next) { if (!this.getOptions || !this.getOptions().includeDeleted) this.where({ deletedAt: null }); if (typeof next === "function") next(); });
export default mongoose.models.CustomerReturn || mongoose.model("CustomerReturn", schema);
