import "server-only";
import mongoose from "mongoose";
import { getNextSequence } from "./Counter.js";
const consumption = new mongoose.Schema({ productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true }, productCode: String, productName: String, componentType: String, plannedQuantity: { type: Number, required: true, min: 0 }, actualQuantity: { type: Number, default: 0 }, unitOfMeasure: String, warehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse" }, standardCost: { type: Number, default: 0 }, actualCost: { type: Number, default: 0 }, stockMovementId: { type: mongoose.Schema.Types.ObjectId, ref: "StockMovement" }, consumedAt: Date, notes: String }, { _id: true });
const labor = new mongoose.Schema({ laborType: String, description: String, plannedHours: Number, actualHours: { type: Number, default: 0 }, hourlyRate: Number, actualCost: { type: Number, default: 0 }, workerId: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, workerName: String, notes: String }, { _id: true });
const output = new mongoose.Schema({ productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true }, productCode: String, productName: String, plannedQuantity: { type: Number, required: true }, actualQuantity: { type: Number, default: 0 }, damagedQuantity: { type: Number, default: 0 }, rejectedQuantity: { type: Number, default: 0 }, unitOfMeasure: String, warehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse" }, qcStatus: { type: String, enum: ["pending", "passed", "failed", "partial"], default: "pending" }, costPerUnit: { type: Number, default: 0 }, batchNumber: String, manufactureDate: Date, expiryDate: Date, stockMovementId: { type: mongoose.Schema.Types.ObjectId, ref: "StockMovement" }, producedAt: Date, notes: String }, { _id: true });
const schema = new mongoose.Schema({
  productionNumber: { type: String, unique: true, trim: true, uppercase: true }, bomId: { type: mongoose.Schema.Types.ObjectId, ref: "BillOfMaterials", required: true }, bomCode: String, bomName: String, finishedProductId: { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true }, finishedProductName: String, finishedProductCode: String, plannedQuantity: { type: Number, required: true, min: 0.01 }, batchMultiplier: Number,
  sourceWarehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse", required: true }, outputWarehouseId: { type: mongoose.Schema.Types.ObjectId, ref: "Warehouse", required: true }, plannedStartDate: Date, plannedEndDate: Date, actualStartDate: Date, actualEndDate: Date,
  status: { type: String, enum: ["draft", "planned", "materials_reserved", "in_progress", "on_hold", "completed", "partially_completed", "cancelled", "closed"], default: "draft" }, priority: { type: String, enum: ["low", "normal", "high", "urgent"], default: "normal" }, consumption: [consumption], labor: [labor], output: [output],
  plannedMaterialCost: { type: Number, default: 0 }, actualMaterialCost: { type: Number, default: 0 }, plannedLaborCost: { type: Number, default: 0 }, actualLaborCost: { type: Number, default: 0 }, overheadCost: { type: Number, default: 0 }, totalPlannedCost: { type: Number, default: 0 }, totalActualCost: { type: Number, default: 0 }, costVariance: { type: Number, default: 0 }, costPerUnit: { type: Number, default: 0 }, completionPercent: { type: Number, default: 0 }, totalProduced: { type: Number, default: 0 }, notes: String, internalNotes: String,
  sourceType: { type: String, enum: ["manual", "sales_order", "min_stock"], default: "manual" }, sourceSalesOrderId: { type: mongoose.Schema.Types.ObjectId, ref: "SalesOrder" }, approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, approvedAt: Date, startedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, completedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, cancelledBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, cancelledAt: Date, cancellationReason: String, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, deletedAt: { type: Date, default: null },
}, { timestamps: true });
schema.index({ status: 1, plannedStartDate: -1 }); schema.index({ finishedProductId: 1 }); schema.index({ bomId: 1 });
schema.pre("save", async function () { if (this.isNew && !this.productionNumber) this.productionNumber = `PO-PRD-${await getNextSequence("production_order")}`; this.plannedMaterialCost = +this.consumption.reduce((sum, item) => sum + item.plannedQuantity * (item.standardCost || 0), 0).toFixed(2); this.actualMaterialCost = +this.consumption.reduce((sum, item) => sum + (item.actualCost || 0), 0).toFixed(2); this.plannedLaborCost = +this.labor.reduce((sum, item) => sum + (item.plannedHours || 0) * (item.hourlyRate || 0), 0).toFixed(2); this.actualLaborCost = +this.labor.reduce((sum, item) => sum + (item.actualCost || 0), 0).toFixed(2); this.totalPlannedCost = +(this.plannedMaterialCost + this.plannedLaborCost + (this.overheadCost || 0)).toFixed(2); this.totalActualCost = +(this.actualMaterialCost + this.actualLaborCost + (this.overheadCost || 0)).toFixed(2); this.costVariance = +(this.totalActualCost - this.totalPlannedCost).toFixed(2); this.totalProduced = +this.output.reduce((sum, item) => sum + (item.actualQuantity || 0), 0).toFixed(4); this.costPerUnit = this.totalProduced > 0 ? +(this.totalActualCost / this.totalProduced).toFixed(2) : 0; this.completionPercent = this.plannedQuantity > 0 ? Math.min(100, +((this.totalProduced / this.plannedQuantity) * 100).toFixed(2)) : 0; });
schema.pre(/^find/, function (next) { if (!this.getOptions || !this.getOptions().includeDeleted) this.where({ deletedAt: null }); if (typeof next === "function") next(); });
export default mongoose.models.ProductionOrder || mongoose.model("ProductionOrder", schema);
