import "server-only";
import SalesOrder from "../models/SalesOrder.js";
import Invoice from "../models/Invoice.js";
import Payment from "../models/Payment.js";
import Customer from "../models/Customer.js";
import StockItem from "../models/StockItem.js";
import Bill from "../models/Bill.js";
import ProductionOrder from "../models/ProductionOrder.js";
import Expense from "../models/Expense.js";

const rounded = (value) => +(value || 0).toFixed(2);
const periodStart = (period) => {
  const now = new Date();
  if (period === "week") return new Date(now.getTime() - 7 * 86400000);
  if (period === "year") return new Date(now.getFullYear(), 0, 1);
  return new Date(now.getFullYear(), now.getMonth(), 1);
};

export async function getDashboardKpis(_req, res) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1);
  const month = new Date(today.getFullYear(), today.getMonth(), 1);
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
  const lastMonthEnd = new Date(today.getFullYear(), today.getMonth(), 0, 23, 59, 59);
  const total = (Model, field, match) => Model.aggregate([{ $match: match }, { $group: { _id: null, total: { $sum: field }, count: { $sum: 1 } } }]);
  const [inv, oldInv, bills, oldBills, exp, oldExp, received, oldReceived, paid, oldPaid, expPaid, oldExpPaid, ordersToday, ordersMonth, pendingApproval, pendingDispatch, ar, overdue, ap, activeProduction, completedProduction, customers, newCustomers, onHold, lowStockItems] = await Promise.all([
    total(Invoice, "$grandTotal", { deletedAt: null, invoiceDate: { $gte: month, $lt: tomorrow } }), total(Invoice, "$grandTotal", { deletedAt: null, invoiceDate: { $gte: lastMonth, $lte: lastMonthEnd } }), total(Bill, "$grandTotal", { deletedAt: null, billDate: { $gte: month, $lt: tomorrow } }), total(Bill, "$grandTotal", { deletedAt: null, billDate: { $gte: lastMonth, $lte: lastMonthEnd } }), total(Expense, "$amount", { deletedAt: null, status: { $ne: "cancelled" }, date: { $gte: month, $lt: tomorrow } }), total(Expense, "$amount", { deletedAt: null, status: { $ne: "cancelled" }, date: { $gte: lastMonth, $lte: lastMonthEnd } }), total(Payment, "$amount", { deletedAt: null, direction: "received", paymentDate: { $gte: month, $lt: tomorrow } }), total(Payment, "$amount", { deletedAt: null, direction: "received", paymentDate: { $gte: lastMonth, $lte: lastMonthEnd } }), total(Payment, "$amount", { deletedAt: null, direction: "paid", paymentDate: { $gte: month, $lt: tomorrow } }), total(Payment, "$amount", { deletedAt: null, direction: "paid", paymentDate: { $gte: lastMonth, $lte: lastMonthEnd } }), total(Expense, "$amount", { deletedAt: null, status: "paid", date: { $gte: month, $lt: tomorrow } }), total(Expense, "$amount", { deletedAt: null, status: "paid", date: { $gte: lastMonth, $lte: lastMonthEnd } }), SalesOrder.countDocuments({ deletedAt: null, orderDate: { $gte: today, $lt: tomorrow } }), SalesOrder.countDocuments({ deletedAt: null, orderDate: { $gte: month } }), SalesOrder.countDocuments({ deletedAt: null, status: "draft" }), SalesOrder.countDocuments({ deletedAt: null, status: "approved" }), total(Invoice, "$balanceDue", { deletedAt: null, paymentStatus: { $in: ["unpaid", "partially_paid", "overdue"] } }), total(Invoice, "$balanceDue", { deletedAt: null, paymentStatus: "overdue" }), total(Bill, "$balanceDue", { deletedAt: null, paymentStatus: { $in: ["unpaid", "partially_paid", "overdue"] } }), ProductionOrder.countDocuments({ deletedAt: null, status: "in_progress" }), ProductionOrder.countDocuments({ deletedAt: null, status: { $in: ["completed", "partially_completed"] }, actualEndDate: { $gte: month } }), Customer.countDocuments({ deletedAt: null, status: "active" }), Customer.countDocuments({ deletedAt: null, createdAt: { $gte: month } }), Customer.countDocuments({ deletedAt: null, "creditStatus.onCreditHold": true }), StockItem.aggregate([{ $group: { _id: "$productId", totalAvailable: { $sum: { $subtract: ["$quantities.onHand", "$quantities.reserved"] } } } }, { $lookup: { from: "products", localField: "_id", foreignField: "_id", as: "product" } }, { $unwind: "$product" }, { $match: { "product.deletedAt": null, "product.canBeSold": true, $expr: { $lte: ["$totalAvailable", "$product.stockLevels.reorderLevel"] } } }, { $project: { productId: "$_id", productCode: "$product.productCode", productName: "$product.name", available: "$totalAvailable", reorderLevel: "$product.stockLevels.reorderLevel" } }, { $limit: 10 }])
  ]);
  const value = (rows) => rows[0]?.total || 0; const growth = (current, previous) => previous !== 0 ? +(((current - previous) / Math.abs(previous)) * 100).toFixed(1) : 0;
  const revenue = value(inv), priorRevenue = value(oldInv), expenses = value(bills) + value(exp), priorExpenses = value(oldBills) + value(oldExp), gross = revenue - expenses, priorGross = priorRevenue - priorExpenses, cash = value(received) - value(paid) - value(expPaid), priorCash = value(oldReceived) - value(oldPaid) - value(oldExpPaid);
  res.json({ success: true, data: { revenue: { thisMonth: rounded(revenue), lastMonth: rounded(priorRevenue), growth: growth(revenue, priorRevenue), invoiceCount: inv[0]?.count || 0 }, grossProfit: { thisMonth: rounded(gross), growth: growth(gross, priorGross) }, cashFlow: { thisMonth: rounded(cash), growth: growth(cash, priorCash) }, orders: { today: ordersToday, thisMonth: ordersMonth, pendingApproval, pendingDispatch }, receivables: { total: rounded(value(ar)), overdue: rounded(value(overdue)), overdueCount: overdue[0]?.count || 0 }, payables: { total: rounded(value(ap)) }, stock: { lowStockCount: lowStockItems.length, lowStockItems }, production: { active: activeProduction, completedThisMonth: completedProduction }, customers: { total: customers, newThisMonth: newCustomers, onHold } } });
}

export async function getRevenueChart(req, res) { const months = Number(req.query.months) || 6; const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth() - months + 1, 1); const rows = await Invoice.aggregate([{ $match: { deletedAt: null, invoiceDate: { $gte: start } } }, { $group: { _id: { year: { $year: "$invoiceDate" }, month: { $month: "$invoiceDate" } }, revenue: { $sum: "$grandTotal" }, count: { $sum: 1 } } }, { $sort: { "_id.year": 1, "_id.month": 1 } }]); const data = Array.from({ length: months }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - months + 1 + index, 1); const row = rows.find((item) => item._id.year === date.getFullYear() && item._id.month === date.getMonth() + 1); return { year: date.getFullYear(), month: date.getMonth() + 1, monthLabel: date.toLocaleDateString("en-LK", { month: "short", year: "2-digit" }), revenue: rounded(row?.revenue), invoiceCount: row?.count || 0 }; }); res.json({ success: true, data }); }
export async function getTopProducts(req, res) { const start = periodStart(req.query.period || "month"); const limit = Number(req.query.limit) || 10; const data = await SalesOrder.aggregate([{ $match: { deletedAt: null, orderDate: { $gte: start }, status: { $nin: ["draft", "cancelled"] } } }, { $unwind: "$items" }, { $group: { _id: "$items.productId", productName: { $first: "$items.productName" }, productCode: { $first: "$items.productCode" }, quantitySold: { $sum: "$items.orderedQuantity" }, revenue: { $sum: { $multiply: ["$items.orderedQuantity", "$items.unitPrice"] } }, orderCount: { $sum: 1 } } }, { $sort: { revenue: -1 } }, { $limit: limit }]); res.json({ success: true, data }); }
export async function getTopCustomers(req, res) { const start = periodStart(req.query.period || "month"); const limit = Number(req.query.limit) || 10; const data = await Invoice.aggregate([{ $match: { deletedAt: null, invoiceDate: { $gte: start } } }, { $group: { _id: "$customerId", customerName: { $first: "$customerSnapshot.name" }, customerCode: { $first: "$customerSnapshot.code" }, totalInvoiced: { $sum: "$grandTotal" }, totalPaid: { $sum: "$amountPaid" }, invoiceCount: { $sum: 1 } } }, { $sort: { totalInvoiced: -1 } }, { $limit: limit }]); res.json({ success: true, data }); }
