import "server-only";
import mongoose from "mongoose";
import ProductionOrder from "../models/ProductionOrder.js";
import BillOfMaterials from "../models/BillOfMaterials.js";
import StockItem from "../models/StockItem.js";
import StockMovement from "../models/StockMovement.js";
import { decreaseStock, increaseStock } from "./stockService.js";
const detail = (query) => query.populate("bomId", "name bomCode version outputQuantity").populate("finishedProductId", "name productCode unitOfMeasure").populate("sourceWarehouseId", "name warehouseCode").populate("outputWarehouseId", "name warehouseCode").populate("consumption.productId", "name productCode unitOfMeasure").populate("consumption.stockMovementId", "movementNumber").populate("output.productId", "name productCode unitOfMeasure").populate("output.stockMovementId", "movementNumber");
export async function createProductionOrder(req, res) {
  const { bomId, plannedQuantity, sourceWarehouseId, outputWarehouseId, plannedStartDate, plannedEndDate, priority, sourceType, sourceSalesOrderId, notes, internalNotes } = req.body;
  const bom = await BillOfMaterials.findById(bomId).populate("components.productId", "productCode name unitOfMeasure costs").populate("finishedProductId", "productCode name unitOfMeasure");
  if (!bom) { res.status(404); throw new Error("BOM not found"); } if (bom.status !== "active") { res.status(400); throw new Error("BOM is not active"); }
  const batchMultiplier = plannedQuantity / bom.outputQuantity;
  const consumption = bom.components.map((item) => ({ productId: item.productId._id, productCode: item.productCode, productName: item.productName, componentType: item.componentType, plannedQuantity: +(item.quantity * batchMultiplier * (1 + (item.wastagePercent || 0) / 100)).toFixed(4), unitOfMeasure: item.unitOfMeasure, warehouseId: sourceWarehouseId, standardCost: item.standardCost || 0 }));
  const labor = bom.labor.map((item) => ({ laborType: item.laborType, description: item.description, plannedHours: (item.hours || 0) * batchMultiplier, hourlyRate: item.hourlyRate || 0 }));
  const output = [{ productId: bom.finishedProductId._id, productCode: bom.finishedProductCode, productName: bom.finishedProductName, plannedQuantity, unitOfMeasure: bom.outputUnitOfMeasure, warehouseId: outputWarehouseId }];
  const po = await ProductionOrder.create({ bomId: bom._id, bomCode: bom.bomCode, bomName: bom.name, finishedProductId: bom.finishedProductId._id, finishedProductName: bom.finishedProductName, finishedProductCode: bom.finishedProductCode, plannedQuantity, batchMultiplier, sourceWarehouseId, outputWarehouseId, plannedStartDate, plannedEndDate, priority: priority || "normal", sourceType: sourceType || "manual", sourceSalesOrderId, consumption, labor, output, notes, internalNotes, status: "draft", createdBy: req.user._id });
  res.status(201).json({ success: true, data: await detail(ProductionOrder.findById(po._id)) });
}
export async function getProductionOrders(req, res) { const { search, status, bomId, finishedProductId, priority, startDate, endDate, page = 1, limit = 20 } = req.query; const filter = {}; if (search) filter.$or = [{ productionNumber: { $regex: search, $options: "i" } }, { finishedProductName: { $regex: search, $options: "i" } }, { bomCode: { $regex: search, $options: "i" } }]; if (status) filter.status = status; if (bomId) filter.bomId = bomId; if (finishedProductId) filter.finishedProductId = finishedProductId; if (priority) filter.priority = priority; if (startDate || endDate) { filter.plannedStartDate = {}; if (startDate) filter.plannedStartDate.$gte = new Date(startDate); if (endDate) filter.plannedStartDate.$lte = new Date(endDate); } const skip = (Number(page) - 1) * Number(limit); const [data, total] = await Promise.all([detail(ProductionOrder.find(filter)).sort({ createdAt: -1 }).skip(skip).limit(Number(limit)), ProductionOrder.countDocuments(filter)]); res.json({ success: true, count: data.length, total, page: Number(page), totalPages: Math.ceil(total / Number(limit)), data }); }
export async function getProductionOrderById(req, res) { const data = await detail(ProductionOrder.findById(req.params.id)).populate("approvedBy", "firstName lastName").populate("startedBy", "firstName lastName").populate("completedBy", "firstName lastName").populate("cancelledBy", "firstName lastName").populate("createdBy", "firstName lastName"); if (!data) { res.status(404); throw new Error("Production order not found"); } res.json({ success: true, data }); }
export async function approveProductionOrder(req, res) { const po = await ProductionOrder.findById(req.params.id); if (!po) { res.status(404); throw new Error("Production order not found"); } if (po.status !== "draft") { res.status(400); throw new Error(`Cannot approve order with status '${po.status}'`); } po.status = "planned"; po.approvedBy = req.user._id; po.approvedAt = new Date(); po.updatedBy = req.user._id; await po.save(); res.json({ success: true, data: po }); }
export async function startProductionOrder(req, res) { const po = await ProductionOrder.findById(req.params.id); if (!po) { res.status(404); throw new Error("Production order not found"); } if (!["planned", "materials_reserved", "on_hold"].includes(po.status)) { res.status(400); throw new Error(`Cannot start order with status '${po.status}'`); } for (const item of po.consumption) { const stock = await StockItem.findOne({ productId: item.productId, warehouseId: item.warehouseId || po.sourceWarehouseId, batchNumber: null }); const available = stock ? stock.quantities.onHand - stock.quantities.reserved : 0; if (available < item.plannedQuantity) { res.status(400); throw new Error(`Insufficient ${item.productName}: need ${item.plannedQuantity}, available ${available}`); } } po.status = "in_progress"; po.actualStartDate = new Date(); po.startedBy = req.user._id; po.updatedBy = req.user._id; await po.save(); res.json({ success: true, data: po }); }
export async function completeProductionOrder(req, res) {
  const { actualConsumption = [], actualLabor = [], output = [], overheadCost = 0, notes } = req.body; const po = await ProductionOrder.findById(req.params.id);
  if (!po) { res.status(404); throw new Error("Production order not found"); } if (!["in_progress", "on_hold"].includes(po.status)) { res.status(400); throw new Error(`Cannot complete order with status '${po.status}'`); }
  const session = await mongoose.startSession();
  try { await session.withTransaction(async () => {
    const consumptionMap = new Map(actualConsumption.map((item) => [item.consumptionItemId, item]));
    for (const item of po.consumption) { const actual = consumptionMap.get(item._id.toString()) || { actualQuantity: item.plannedQuantity }; const quantity = Number(actual.actualQuantity) || 0; if (quantity > 0) { const result = await decreaseStock({ productId: item.productId, warehouseId: item.warehouseId || po.sourceWarehouseId, quantity, movementType: "production_consume", sourceDocument: { type: "production_order", id: po._id, number: po.productionNumber }, reason: `Material consumed for ${po.productionNumber}`, notes: actual.notes, userId: req.user._id, session }); item.actualQuantity = quantity; item.actualCost = +(quantity * result.stockItem.costPerUnit).toFixed(2); item.stockMovementId = result.movement._id; item.consumedAt = new Date(); } }
    const laborMap = new Map(po.labor.map((item) => [item._id.toString(), item]));
    for (const actual of actualLabor) { if (actual.laborLogId) { const item = laborMap.get(actual.laborLogId); if (item) { item.actualHours = Number(actual.actualHours) || 0; item.actualCost = +(item.actualHours * (actual.hourlyRate ?? item.hourlyRate ?? 0)).toFixed(2); if (actual.hourlyRate !== undefined) item.hourlyRate = Number(actual.hourlyRate); if (actual.workerId) item.workerId = actual.workerId; } } else po.labor.push({ laborType: actual.laborType || "general", description: actual.description, plannedHours: 0, actualHours: Number(actual.actualHours) || 0, hourlyRate: Number(actual.hourlyRate) || 0, actualCost: +((Number(actual.actualHours) || 0) * (Number(actual.hourlyRate) || 0)).toFixed(2), workerId: actual.workerId }); }
    const totalActualCost = po.consumption.reduce((sum, item) => sum + (item.actualCost || 0), 0) + po.labor.reduce((sum, item) => sum + (item.actualCost || 0), 0) + (overheadCost || 0); let totalProduced = 0;
    for (let index = 0; index < output.length; index += 1) { const actual = output[index]; const item = po.output[index] || po.output[0]; const quantity = Number(actual.actualQuantity) || 0; const damaged = Number(actual.damagedQuantity) || 0; totalProduced += quantity; item.actualQuantity = quantity; item.damagedQuantity = damaged; item.rejectedQuantity = Number(actual.rejectedQuantity) || 0; item.qcStatus = actual.qcStatus || "passed"; item.batchNumber = actual.batchNumber; item.manufactureDate = actual.manufactureDate ? new Date(actual.manufactureDate) : new Date(); item.expiryDate = actual.expiryDate ? new Date(actual.expiryDate) : undefined; item.producedAt = new Date(); const costPerUnit = totalProduced > 0 ? totalActualCost / totalProduced : 0; item.costPerUnit = +costPerUnit.toFixed(2); if (quantity > 0) { const result = await increaseStock({ productId: item.productId, warehouseId: item.warehouseId || po.outputWarehouseId, quantity, costPerUnit: +costPerUnit.toFixed(2), movementType: "production_output", batchNumber: actual.batchNumber || null, sourceDocument: { type: "production_order", id: po._id, number: po.productionNumber }, reason: `Produced via ${po.productionNumber}`, notes: actual.notes, userId: req.user._id, session }); item.stockMovementId = result.movement._id; } if (damaged > 0) { await StockMovement.create([{ productId: item.productId, productCode: item.productCode, productName: item.productName, movementType: "production_scrap", direction: "out", quantity: damaged, unitOfMeasure: item.unitOfMeasure, warehouseId: item.warehouseId || po.outputWarehouseId, sourceDocument: { type: "production_order", id: po._id, number: po.productionNumber }, reason: "Damaged during production", performedBy: req.user._id, balanceBefore: 0, balanceAfter: 0 }], { session }); } }
    po.overheadCost = overheadCost; po.status = totalProduced >= po.plannedQuantity ? "completed" : "partially_completed"; po.actualEndDate = new Date(); po.completedBy = req.user._id; po.updatedBy = req.user._id; if (notes) po.notes = po.notes ? `${po.notes}\n---\n${notes}` : notes; await po.save({ session });
  }); const data = await detail(ProductionOrder.findById(po._id)); res.json({ success: true, message: `Production ${po.status === "completed" ? "completed" : "partially completed"}. Stock updated.`, data }); } catch (error) { res.status(400); throw new Error(error.message || "Failed to complete production"); } finally { await session.endSession(); }
}
export async function cancelProductionOrder(req, res) { const po = await ProductionOrder.findById(req.params.id); if (!po) { res.status(404); throw new Error("Production order not found"); } if (!["draft", "planned", "materials_reserved", "in_progress", "on_hold"].includes(po.status)) { res.status(400); throw new Error(`Cannot cancel order with status '${po.status}'`); } po.status = "cancelled"; po.cancelledBy = req.user._id; po.cancelledAt = new Date(); po.cancellationReason = req.body.reason; po.updatedBy = req.user._id; await po.save(); res.json({ success: true, data: po }); }
export async function holdProductionOrder(req, res) { const po = await ProductionOrder.findById(req.params.id); if (!po) { res.status(404); throw new Error("Production order not found"); } if (!["planned", "in_progress", "materials_reserved"].includes(po.status)) { res.status(400); throw new Error(`Cannot hold order with status '${po.status}'`); } po.status = "on_hold"; if (req.body.reason) po.internalNotes = po.internalNotes ? `${po.internalNotes}\nHOLD: ${req.body.reason}` : `HOLD: ${req.body.reason}`; po.updatedBy = req.user._id; await po.save(); res.json({ success: true, data: po }); }
export async function deleteProductionOrder(req, res) { const po = await ProductionOrder.findById(req.params.id); if (!po) { res.status(404); throw new Error("Production order not found"); } if (po.status !== "draft") { res.status(400); throw new Error("Only draft orders can be deleted"); } po.deletedAt = new Date(); await po.save(); res.json({ success: true, message: "Draft production order deleted" }); }
