import "server-only";
import SalesOrder from "../models/SalesOrder.js";
import Invoice from "../models/Invoice.js";
import Payment from "../models/Payment.js";
import StockItem from "../models/StockItem.js";
import StockMovement from "../models/StockMovement.js";
import Product from "../models/Product.js";
import ProductionOrder from "../models/ProductionOrder.js";
import DamageRecord from "../models/DamageRecord.js";
import CustomerReturn from "../models/CustomerReturn.js";
import Bill from "../models/Bill.js";
import Expense from "../models/Expense.js";
import Employee from "../models/Employee.js";
import Attendance from "../models/Attendance.js";
import LeaveRequest from "../models/LeaveRequest.js";
import Payroll from "../models/Payroll.js";

function period(query, fallbackDays) {
  const start = query.startDate ? new Date(query.startDate) : fallbackDays ? new Date(Date.now() - fallbackDays * 86400000) : new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  const end = query.endDate ? new Date(query.endDate) : new Date();
  end.setHours(23, 59, 59, 999);
  return { start, end };
}
const money = (value) => +(value || 0).toFixed(2);

export async function getSalesSummary(req, res) {
  const { start, end } = period(req.query);
  const match = { deletedAt: null, orderDate: { $gte: start, $lte: end } };
  const [ordersAgg, statusBreakdown, invoicesAgg, paymentsAgg] = await Promise.all([
    SalesOrder.aggregate([{ $match: { ...match, status: { $nin: ["draft", "cancelled"] } } }, { $group: { _id: null, totalOrders: { $sum: 1 }, totalValue: { $sum: "$grandTotal" }, avgOrderValue: { $avg: "$grandTotal" } } }]),
    SalesOrder.aggregate([{ $match: match }, { $group: { _id: "$status", count: { $sum: 1 }, value: { $sum: "$grandTotal" } } }]),
    Invoice.aggregate([{ $match: { deletedAt: null, invoiceDate: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$grandTotal" }, paid: { $sum: "$amountPaid" }, balance: { $sum: "$balanceDue" }, count: { $sum: 1 } } }]),
    Payment.aggregate([{ $match: { deletedAt: null, direction: "received", paymentDate: { $gte: start, $lte: end } } }, { $group: { _id: null, collected: { $sum: "$amount" }, count: { $sum: 1 } } }]),
  ]);
  const invoices = invoicesAgg[0] || { total: 0, paid: 0, balance: 0, count: 0 };
  const payments = paymentsAgg[0] || { collected: 0, count: 0 };
  res.json({ success: true, data: { period: { startDate: start, endDate: end }, orders: ordersAgg[0] || { totalOrders: 0, totalValue: 0, avgOrderValue: 0 }, statusBreakdown, invoices: { ...invoices, total: money(invoices.total), paid: money(invoices.paid), balance: money(invoices.balance) }, payments: { collected: money(payments.collected), count: payments.count }, collectionEfficiency: invoices.total > 0 ? +((payments.collected / invoices.total) * 100).toFixed(1) : 0 } });
}

export async function getSalesByProduct(req, res) {
  const { start, end } = period(req.query); const limit = req.query.limit || 50;
  const data = await SalesOrder.aggregate([{ $match: { deletedAt: null, orderDate: { $gte: start, $lte: end }, status: { $nin: ["draft", "cancelled"] } } }, { $unwind: "$items" }, { $group: { _id: "$items.productId", productCode: { $first: "$items.productCode" }, productName: { $first: "$items.productName" }, quantitySold: { $sum: "$items.orderedQuantity" }, avgPrice: { $avg: "$items.unitPrice" }, grossRevenue: { $sum: { $multiply: ["$items.orderedQuantity", "$items.unitPrice"] } }, totalDiscount: { $sum: { $multiply: ["$items.orderedQuantity", "$items.unitPrice", { $divide: [{ $ifNull: ["$items.discountPercent", 0] }, 100] }] } }, orderCount: { $sum: 1 } } }, { $addFields: { netRevenue: { $subtract: ["$grossRevenue", "$totalDiscount"] } } }, { $sort: { netRevenue: -1 } }, { $limit: Number(limit) }]);
  res.json({ success: true, data });
}

export async function getSalesByCustomer(req, res) {
  const { start, end } = period(req.query); const limit = req.query.limit || 50;
  const data = await SalesOrder.aggregate([{ $match: { deletedAt: null, orderDate: { $gte: start, $lte: end }, status: { $nin: ["draft", "cancelled"] } } }, { $group: { _id: "$customerId", customerCode: { $first: "$customerSnapshot.code" }, customerName: { $first: "$customerSnapshot.name" }, orderCount: { $sum: 1 }, totalOrdered: { $sum: "$grandTotal" }, avgOrderValue: { $avg: "$grandTotal" } } }, { $sort: { totalOrdered: -1 } }, { $limit: Number(limit) }]);
  const payments = await Invoice.aggregate([{ $match: { deletedAt: null, customerId: { $in: data.map((row) => row._id) }, invoiceDate: { $gte: start, $lte: end } } }, { $group: { _id: "$customerId", invoiced: { $sum: "$grandTotal" }, paid: { $sum: "$amountPaid" }, outstanding: { $sum: "$balanceDue" } } }]);
  const mapped = new Map(payments.map((row) => [row._id.toString(), row]));
  res.json({ success: true, data: data.map((row) => { const payment = mapped.get(row._id.toString()) || {}; return { ...row, totalOrdered: money(row.totalOrdered), avgOrderValue: money(row.avgOrderValue), invoiced: money(payment.invoiced), paid: money(payment.paid), outstanding: money(payment.outstanding) }; }) });
}

export async function getSalesTrend(req, res) {
  const { start, end } = period(req.query, 30); const { groupBy = "day" } = req.query;
  const group = groupBy === "month" ? { year: { $year: "$orderDate" }, month: { $month: "$orderDate" } } : groupBy === "week" ? { year: { $year: "$orderDate" }, week: { $week: "$orderDate" } } : { year: { $year: "$orderDate" }, month: { $month: "$orderDate" }, day: { $dayOfMonth: "$orderDate" } };
  const data = await SalesOrder.aggregate([{ $match: { deletedAt: null, orderDate: { $gte: start, $lte: end }, status: { $nin: ["draft", "cancelled"] } } }, { $group: { _id: group, count: { $sum: 1 }, total: { $sum: "$grandTotal" } } }, { $sort: { "_id.year": 1, "_id.month": 1, "_id.week": 1, "_id.day": 1 } }]);
  res.json({ success: true, data: data.map((row) => ({ label: groupBy === "month" ? `${row._id.year}-${String(row._id.month).padStart(2, "0")}` : groupBy === "week" ? `${row._id.year}-W${row._id.week}` : `${row._id.year}-${String(row._id.month).padStart(2, "0")}-${String(row._id.day).padStart(2, "0")}`, count: row.count, total: money(row.total) })) });
}

export async function getStockValuation(req, res) {
  const match = req.query.warehouseId ? { warehouseId: req.query.warehouseId } : {};
  const data = await StockItem.aggregate([{ $match: match }, { $lookup: { from: "products", localField: "productId", foreignField: "_id", as: "product" } }, { $unwind: "$product" }, { $match: { "product.deletedAt": null } }, { $lookup: { from: "warehouses", localField: "warehouseId", foreignField: "_id", as: "warehouse" } }, { $unwind: "$warehouse" }, { $project: { productId: "$product._id", productCode: "$product.productCode", productName: "$product.name", productType: "$product.productType", warehouseName: "$warehouse.name", warehouseCode: "$warehouse.warehouseCode", onHand: "$quantities.onHand", reserved: "$quantities.reserved", available: { $subtract: ["$quantities.onHand", "$quantities.reserved"] }, costPerUnit: 1, totalValue: { $multiply: ["$quantities.onHand", "$costPerUnit"] }, batchNumber: 1 } }, { $sort: { totalValue: -1 } }]);
  const byType = data.reduce((all, row) => { const type = row.productType || "unknown"; all[type] ||= { type, units: 0, value: 0, items: 0 }; all[type].units += row.onHand || 0; all[type].value += row.totalValue || 0; all[type].items += 1; return all; }, {});
  res.json({ success: true, data: { summary: { totalValue: money(data.reduce((sum, row) => sum + (row.totalValue || 0), 0)), totalUnits: data.reduce((sum, row) => sum + (row.onHand || 0), 0), productCount: data.length }, byProductType: Object.values(byType).map((row) => ({ ...row, value: money(row.value) })), items: data.map((row) => ({ ...row, totalValue: money(row.totalValue) })) } });
}

export async function getStockMovement(req, res) { const { startDate, endDate, productId, warehouseId, limit = 200 } = req.query; const filter = {}; if (productId) filter.productId = productId; if (warehouseId) filter.warehouseId = warehouseId; if (startDate || endDate) { filter.createdAt = {}; if (startDate) filter.createdAt.$gte = new Date(startDate); if (endDate) { const end = new Date(endDate); end.setHours(23, 59, 59, 999); filter.createdAt.$lte = end; } } const data = await StockMovement.find(filter).populate("productId", "name productCode").populate("warehouseId", "name warehouseCode").populate("performedBy", "firstName lastName").sort({ createdAt: -1 }).limit(Number(limit)); res.json({ success: true, count: data.length, data }); }

export async function getSlowFastMovers(req, res) { const days = req.query.days || 90; const since = new Date(Date.now() - Number(days) * 86400000); const rows = await StockMovement.aggregate([{ $match: { createdAt: { $gte: since }, movementType: { $in: ["sale_dispatch"] }, direction: "out" } }, { $group: { _id: "$productId", unitsSold: { $sum: "$quantity" }, movements: { $sum: 1 } } }, { $lookup: { from: "products", localField: "_id", foreignField: "_id", as: "product" } }, { $unwind: "$product" }, { $match: { "product.deletedAt": null, "product.canBeSold": true } }, { $project: { productId: "$product._id", productCode: "$product.productCode", productName: "$product.name", unitsSold: 1, movements: 1, unitPrice: "$product.basePrice", revenue: { $multiply: ["$unitsSold", "$product.basePrice"] } } }, { $sort: { revenue: -1 } }]); const totalRevenue = rows.reduce((sum, row) => sum + row.revenue, 0); let cumulative = 0; const classified = rows.map((row) => { cumulative += row.revenue; const percent = totalRevenue > 0 ? cumulative / totalRevenue * 100 : 0; return { ...row, revenue: money(row.revenue), cumulativePercent: +percent.toFixed(1), abcClass: percent <= 80 ? "A" : percent <= 95 ? "B" : "C" }; }); const sold = new Set(rows.map((row) => row._id.toString())); const allSellable = await Product.find({ deletedAt: null, canBeSold: true, status: "active" }).select("_id productCode name basePrice"); const dead = allSellable.filter((item) => !sold.has(item._id.toString())).map((item) => ({ productId: item._id, productCode: item.productCode, productName: item.name, unitsSold: 0, revenue: 0, abcClass: "D" })); res.json({ success: true, data: { period: { days: Number(days), since }, totalRevenue: money(totalRevenue), classification: { A: classified.filter((row) => row.abcClass === "A"), B: classified.filter((row) => row.abcClass === "B"), C: classified.filter((row) => row.abcClass === "C"), D: dead }, summary: { fastMovers: classified.filter((row) => row.abcClass === "A").length, mediumMovers: classified.filter((row) => row.abcClass === "B").length, slowMovers: classified.filter((row) => row.abcClass === "C").length, deadStock: dead.length } } }); }

export async function getLowStockReport(_req, res) { const data = await StockItem.aggregate([{ $group: { _id: "$productId", totalOnHand: { $sum: "$quantities.onHand" }, totalReserved: { $sum: "$quantities.reserved" } } }, { $lookup: { from: "products", localField: "_id", foreignField: "_id", as: "product" } }, { $unwind: "$product" }, { $match: { "product.deletedAt": null } }, { $project: { productId: "$_id", productCode: "$product.productCode", productName: "$product.name", productType: "$product.productType", onHand: "$totalOnHand", reserved: "$totalReserved", available: { $subtract: ["$totalOnHand", "$totalReserved"] }, reorderLevel: "$product.stockLevels.reorderLevel", minimumStock: "$product.stockLevels.minimumStock" } }, { $addFields: { shortage: { $subtract: ["$reorderLevel", "$available"] }, isCritical: { $lte: ["$available", "$minimumStock"] } } }, { $match: { $expr: { $lte: ["$available", "$reorderLevel"] } } }, { $sort: { shortage: -1 } }]); res.json({ success: true, data }); }

export async function getProductionSummary(req, res) { const { start, end } = period(req.query); const match = { deletedAt: null, createdAt: { $gte: start, $lte: end } }; const [summary, byStatus] = await Promise.all([ProductionOrder.aggregate([{ $match: match }, { $group: { _id: null, totalOrders: { $sum: 1 }, totalPlannedQty: { $sum: "$plannedQuantity" }, totalProducedQty: { $sum: "$totalProduced" }, totalPlannedCost: { $sum: "$totalPlannedCost" }, totalActualCost: { $sum: "$totalActualCost" }, totalVariance: { $sum: "$costVariance" } } }]), ProductionOrder.aggregate([{ $match: match }, { $group: { _id: "$status", count: { $sum: 1 }, quantity: { $sum: "$plannedQuantity" } } }])]); const s = summary[0] || { totalOrders: 0, totalPlannedQty: 0, totalProducedQty: 0, totalPlannedCost: 0, totalActualCost: 0, totalVariance: 0 }; res.json({ success: true, data: { period: { start, end }, summary: { ...s, yieldPercent: s.totalPlannedQty > 0 ? +(s.totalProducedQty / s.totalPlannedQty * 100).toFixed(1) : 0, variancePercent: s.totalPlannedCost > 0 ? +(s.totalVariance / s.totalPlannedCost * 100).toFixed(1) : 0, totalPlannedCost: money(s.totalPlannedCost), totalActualCost: money(s.totalActualCost), totalVariance: money(s.totalVariance) }, byStatus } }); }
export async function getProductionByProduct(req, res) { const { start, end } = period(req.query); const data = await ProductionOrder.aggregate([{ $match: { deletedAt: null, status: { $in: ["completed", "partially_completed"] }, actualEndDate: { $gte: start, $lte: end } } }, { $group: { _id: "$finishedProductId", productCode: { $first: "$finishedProductCode" }, productName: { $first: "$finishedProductName" }, orderCount: { $sum: 1 }, totalPlanned: { $sum: "$plannedQuantity" }, totalProduced: { $sum: "$totalProduced" }, totalPlannedCost: { $sum: "$totalPlannedCost" }, totalActualCost: { $sum: "$totalActualCost" }, avgCostPerUnit: { $avg: "$costPerUnit" } } }, { $addFields: { yieldPercent: { $cond: [{ $gt: ["$totalPlanned", 0] }, { $multiply: [{ $divide: ["$totalProduced", "$totalPlanned"] }, 100] }, 0] } } }, { $sort: { totalProduced: -1 } }]); res.json({ success: true, data: data.map((row) => ({ ...row, totalActualCost: money(row.totalActualCost), totalPlannedCost: money(row.totalPlannedCost), avgCostPerUnit: money(row.avgCostPerUnit), yieldPercent: +row.yieldPercent.toFixed(1) })) }); }
export async function getProductionWastage(req, res) { const { start, end } = period(req.query); const byProduct = await DamageRecord.aggregate([{ $match: { deletedAt: null, source: "production_reject", createdAt: { $gte: start, $lte: end } } }, { $group: { _id: "$productId", productCode: { $first: "$productCode" }, productName: { $first: "$productName" }, count: { $sum: 1 }, totalQuantity: { $sum: "$quantity" }, totalValue: { $sum: "$totalValue" } } }, { $sort: { totalValue: -1 } }]); res.json({ success: true, data: { totalWastageValue: money(byProduct.reduce((sum, row) => sum + row.totalValue, 0)), totalIncidents: byProduct.length, byProduct: byProduct.map((row) => ({ ...row, totalValue: money(row.totalValue) })) } }); }
export async function getReturnsSummary(req, res) { const { start, end } = period(req.query); const match = { deletedAt: null, requestDate: { $gte: start, $lte: end } }; const [summary, byReason, byCustomer, byStatus] = await Promise.all([CustomerReturn.aggregate([{ $match: match }, { $group: { _id: null, totalReturns: { $sum: 1 }, totalValue: { $sum: "$totalReturnValue" }, totalRefunded: { $sum: "$netRefundAmount" } } }]), CustomerReturn.aggregate([{ $match: match }, { $unwind: "$items" }, { $group: { _id: "$items.reason", count: { $sum: 1 }, value: { $sum: { $multiply: ["$items.quantityReturned", "$items.unitPrice"] } } } }, { $sort: { count: -1 } }]), CustomerReturn.aggregate([{ $match: match }, { $group: { _id: "$customerId", customerName: { $first: "$customerSnapshot.name" }, customerCode: { $first: "$customerSnapshot.code" }, returnCount: { $sum: 1 }, totalValue: { $sum: "$totalReturnValue" } } }, { $sort: { returnCount: -1 } }, { $limit: 10 }]), CustomerReturn.aggregate([{ $match: match }, { $group: { _id: "$status", count: { $sum: 1 } } }])]); res.json({ success: true, data: { summary: summary[0] || { totalReturns: 0, totalValue: 0, totalRefunded: 0 }, byReason, byCustomer, byStatus } }); }
export async function getDamagesReport(req, res) { const { start, end } = period(req.query); const match = { deletedAt: null, createdAt: { $gte: start, $lte: end } }; const [summary, bySource, byProduct] = await Promise.all([DamageRecord.aggregate([{ $match: match }, { $group: { _id: null, count: { $sum: 1 }, totalValue: { $sum: "$totalValue" } } }]), DamageRecord.aggregate([{ $match: match }, { $group: { _id: "$source", count: { $sum: 1 }, value: { $sum: "$totalValue" } } }, { $sort: { value: -1 } }]), DamageRecord.aggregate([{ $match: match }, { $group: { _id: "$productId", productCode: { $first: "$productCode" }, productName: { $first: "$productName" }, count: { $sum: 1 }, quantity: { $sum: "$quantity" }, value: { $sum: "$totalValue" } } }, { $sort: { value: -1 } }, { $limit: 20 }])]); res.json({ success: true, data: { summary: summary[0] || { count: 0, totalValue: 0 }, bySource, byProduct } }); }

const aging = (Model) => Model.aggregate([{ $match: { deletedAt: null, paymentStatus: { $in: ["unpaid", "partially_paid", "overdue"] } } }, { $group: { _id: null, current: { $sum: { $cond: [{ $eq: ["$agingBucket", "current"] }, "$balanceDue", 0] } }, b1_30: { $sum: { $cond: [{ $eq: ["$agingBucket", "1_30"] }, "$balanceDue", 0] } }, b31_60: { $sum: { $cond: [{ $eq: ["$agingBucket", "31_60"] }, "$balanceDue", 0] } }, b61_90: { $sum: { $cond: [{ $eq: ["$agingBucket", "61_90"] }, "$balanceDue", 0] } }, b91_plus: { $sum: { $cond: [{ $eq: ["$agingBucket", "91_plus"] }, "$balanceDue", 0] } }, total: { $sum: "$balanceDue" } } }]);
export async function getFinancialSnapshot(req, res) { const { start, end } = period(req.query); const [revenue, bills, expenses, collected, paid, expensesPaid, ar, ap] = await Promise.all([Invoice.aggregate([{ $match: { deletedAt: null, invoiceDate: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$grandTotal" } } }]), Bill.aggregate([{ $match: { deletedAt: null, billDate: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$grandTotal" } } }]), Expense.aggregate([{ $match: { deletedAt: null, status: { $ne: "cancelled" }, date: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Payment.aggregate([{ $match: { deletedAt: null, direction: "received", paymentDate: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Payment.aggregate([{ $match: { deletedAt: null, direction: "paid", paymentDate: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), Expense.aggregate([{ $match: { deletedAt: null, status: "paid", date: { $gte: start, $lte: end } } }, { $group: { _id: null, total: { $sum: "$amount" } } }]), aging(Invoice), aging(Bill)]); const revenueTotal = revenue[0]?.total || 0; const expensesTotal = (bills[0]?.total || 0) + (expenses[0]?.total || 0); const collectedTotal = collected[0]?.total || 0; const paidTotal = (paid[0]?.total || 0) + (expensesPaid[0]?.total || 0); res.json({ success: true, data: { period: { start, end }, revenue: money(revenueTotal), expenses: money(expensesTotal), grossProfit: money(revenueTotal - expensesTotal), collected: money(collectedTotal), paid: money(paidTotal), netCashFlow: money(collectedTotal - paidTotal), collectionEfficiency: revenueTotal > 0 ? +(collectedTotal / revenueTotal * 100).toFixed(1) : 0, accountsReceivable: ar[0] || { current: 0, b1_30: 0, b31_60: 0, b61_90: 0, b91_plus: 0, total: 0 }, accountsPayable: ap[0] || { current: 0, b1_30: 0, b31_60: 0, b61_90: 0, b91_plus: 0, total: 0 } } }); }
export async function getProfitAndLoss(req, res) { const filter = {}; if (req.query.startDate && req.query.startDate !== "undefined") filter.$gte = new Date(req.query.startDate); if (req.query.endDate && req.query.endDate !== "undefined") filter.$lte = new Date(req.query.endDate); const invoices = await Invoice.find({ status: { $nin: ["draft", "void", "cancelled"] }, deletedAt: null, ...(Object.keys(filter).length ? { invoiceDate: filter } : {}) }).populate("items.productId"); let grossSales = 0; let totalDiscounts = 0; let cogs = 0; invoices.forEach((invoice) => { grossSales += invoice.subtotal || 0; totalDiscounts += invoice.totalDiscount || 0; invoice.items.forEach((item) => { cogs += item.quantity * (item.productId?.purchasePrice || 0); }); }); const expenseRows = await Expense.aggregate([{ $match: { status: { $ne: "cancelled" }, deletedAt: null, ...(Object.keys(filter).length ? { date: filter } : {}) } }, { $group: { _id: "$category", total: { $sum: "$amount" } } }, { $sort: { total: -1 } }]); const totalExpenses = expenseRows.reduce((sum, row) => sum + row.total, 0); const revenue = grossSales - totalDiscounts; const grossProfit = revenue - cogs; res.json({ success: true, data: { revenue: { grossSales: money(grossSales), totalDiscounts: money(totalDiscounts), totalReturns: 0, totalRevenue: money(revenue) }, cogs: { productCosts: money(cogs), totalCogs: money(cogs) }, expenses: { breakdown: expenseRows.map((row) => ({ _id: row._id || "Uncategorized", amount: money(row.total) })), totalExpenses: money(totalExpenses) }, grossProfit: money(grossProfit), netProfit: money(grossProfit - totalExpenses) } }); }
export async function getHeadcountReport(_req, res) { const [total, byDepartment, byDesignation, byEmploymentType, byStatus] = await Promise.all([Employee.countDocuments({ deletedAt: null }), Employee.aggregate([{ $match: { deletedAt: null } }, { $group: { _id: "$departmentId", count: { $sum: 1 } } }, { $lookup: { from: "departments", localField: "_id", foreignField: "_id", as: "dept" } }, { $unwind: { path: "$dept", preserveNullAndEmptyArrays: true } }, { $project: { name: "$dept.name", count: 1 } }, { $sort: { count: -1 } }]), Employee.aggregate([{ $match: { deletedAt: null } }, { $group: { _id: "$designationId", count: { $sum: 1 } } }, { $lookup: { from: "designations", localField: "_id", foreignField: "_id", as: "des" } }, { $unwind: { path: "$des", preserveNullAndEmptyArrays: true } }, { $project: { name: "$des.name", count: 1 } }, { $sort: { count: -1 } }]), Employee.aggregate([{ $match: { deletedAt: null } }, { $group: { _id: "$employmentType", count: { $sum: 1 } } }]), Employee.aggregate([{ $match: { deletedAt: null } }, { $group: { _id: "$status", count: { $sum: 1 } } }])]); res.json({ success: true, data: { total, byDepartment, byDesignation, byEmploymentType, byStatus } }); }
export async function getAttendanceReport(req, res) { const { start, end } = period(req.query); const [summary, byEmployee] = await Promise.all([Attendance.aggregate([{ $match: { date: { $gte: start, $lte: end } } }, { $group: { _id: "$status", count: { $sum: 1 } } }]), Attendance.aggregate([{ $match: { date: { $gte: start, $lte: end } } }, { $group: { _id: "$employeeId", employeeName: { $first: "$employeeName" }, employeeCode: { $first: "$employeeCode" }, present: { $sum: { $cond: [{ $eq: ["$status", "present"] }, 1, 0] } }, absent: { $sum: { $cond: [{ $eq: ["$status", "absent"] }, 1, 0] } }, late: { $sum: { $cond: [{ $eq: ["$status", "late"] }, 1, 0] } }, leave: { $sum: { $cond: [{ $eq: ["$status", "leave"] }, 1, 0] } }, halfDay: { $sum: { $cond: [{ $eq: ["$status", "half_day"] }, 1, 0] } }, totalLateMinutes: { $sum: "$lateMinutes" }, totalOvertimeMinutes: { $sum: "$overtimeMinutes" } } }, { $sort: { present: -1 } }])]); res.json({ success: true, data: { period: { start, end }, summary, byEmployee } }); }
export async function getLeavePatternsReport(req, res) { const year = Number(req.query.year) || new Date().getFullYear(); const start = new Date(year, 0, 1); const end = new Date(year, 11, 31, 23, 59, 59); const match = { deletedAt: null, status: "approved", fromDate: { $gte: start, $lte: end } }; const [byType, byMonth, topTakers] = await Promise.all([LeaveRequest.aggregate([{ $match: match }, { $group: { _id: "$leaveType", count: { $sum: 1 }, totalDays: { $sum: "$numberOfDays" } } }, { $sort: { totalDays: -1 } }]), LeaveRequest.aggregate([{ $match: match }, { $group: { _id: { $month: "$fromDate" }, count: { $sum: 1 }, totalDays: { $sum: "$numberOfDays" } } }, { $sort: { _id: 1 } }]), LeaveRequest.aggregate([{ $match: match }, { $group: { _id: "$employeeId", employeeName: { $first: "$employeeName" }, employeeCode: { $first: "$employeeCode" }, leaveCount: { $sum: 1 }, totalDays: { $sum: "$numberOfDays" } } }, { $sort: { totalDays: -1 } }, { $limit: 10 }])]); res.json({ success: true, data: { year, byType, byMonth, topTakers } }); }
export async function getPayrollSummaryReport(req, res) { const year = Number(req.query.year) || new Date().getFullYear(); const monthly = await Payroll.aggregate([{ $match: { deletedAt: null, periodYear: year } }, { $sort: { periodMonth: 1 } }, { $project: { periodMonth: 1, periodYear: 1, status: 1, totalEmployees: 1, totalGrossEarnings: 1, totalDeductions: 1, totalEpfEmployee: 1, totalEpfEmployer: 1, totalEtf: 1, totalApit: 1, totalNetPay: 1 } }]); const totals = monthly.reduce((sum, item) => ({ gross: sum.gross + (item.totalGrossEarnings || 0), deductions: sum.deductions + (item.totalDeductions || 0), netPay: sum.netPay + (item.totalNetPay || 0), epfEmployee: sum.epfEmployee + (item.totalEpfEmployee || 0), epfEmployer: sum.epfEmployer + (item.totalEpfEmployer || 0), etf: sum.etf + (item.totalEtf || 0), apit: sum.apit + (item.totalApit || 0) }), { gross: 0, deductions: 0, netPay: 0, epfEmployee: 0, epfEmployer: 0, etf: 0, apit: 0 }); res.json({ success: true, data: { year, monthly, yearTotals: Object.fromEntries(Object.entries(totals).map(([key, value]) => [key, money(value)])) } }); }
